name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build and pack
        id: build
        run: |
          npm run build
          package=$(npm pack)
          echo "package=$package" >> $GITHUB_OUTPUT

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.build.outputs.package }}

  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        name: Download package
        with:
          pattern: package
          path: package.tgz
          merge-multiple: true

      - name: Extract package
        run: tar -xzvf package.tgz

      - name: Push package
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: package
          build_dir: package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
