name: Test
on:
  push:
    branches: [master]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build doc
        run: npm run doc

      - name: Upload doc
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: doc

  push:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/download-artifact@v4
        name: Download doc
        with:
          pattern: doc
          path: doc
          merge-multiple: true

      - name: Push doc
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: doc
          build_dir: doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
